apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-configmap
spec:
  selector:
    matchLabels:
      app: springboot-configmap
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-configmap
    spec:
      volumes:
        - name: config-data
          configMap:
            name: spring-app-config
            items:
              - key:  application.properties
                path: application.properties
      containers:
        - name: springboot-configmap
          image: springboot-k8s:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_LOCATION
              value: /config/application.properties
          volumeMounts:
            - name: config-data
              mountPath: /config
      restartPolicy: Always