kind: Service
apiVersion: v1
metadata:
  name: springboot-configmap
spec:
  selector:
    app: springboot-configmap
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30083
  type: NodePort